[brmesh]
key = [0x37, 0x39, 0x39, 0x36]

[artnet]
# ArtNet Universe (QLC+ Univ 3 = ArtNet 512)
universe = 512

# DMX start address (1-based)
start_address = 1

# Number of channels to listen for
channels = 72

# Number of lights (each 4 channels: R,G,B,Brightness)
num_lights = 24

# Minimum time between MQTT sends (ms)
throttle_ms = 50

[mqtt]
host = 127.0.0.1
port = 1883
